name: CI

on:
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - '**' 
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Create appsettings.Production.json
        env:
          APPSETTINGS_JSON: ${{ secrets.APPSETTINGS_PRODUCTION }}
        run: echo "$APPSETTINGS_JSON" > Personal_Finance_Management/Personal_Finance_Management.Api/appsettings.Production.json

      - name: Restore dependencies
        run: dotnet restore Personal_Finance_Management/Personal_Finance_Management.sln

      - name: Build
        run: dotnet build Personal_Finance_Management/Personal_Finance_Management.sln --no-restore

      - name: Run tests
        run: dotnet test Personal_Finance_Management/Personal_Finance_Management.sln --no-build --verbosity normal
