name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.0'
          
      - name:  appsettings.Production.json
        run: echo "${{ secrets.APPSETTINGS_PRODUCTION }}" > .Personal_Finance_Management/Personal_Finance_Management.Api/appsettings.json
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
      